source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target 'SWS' do
pod "SnapKit"
pod "Bugly"
#pod "WCDB.swift"
pod "Hyphenate"
pod "YYKit", '0.9.6'
pod "Qiniu", "~> 7.2.3"
pod "SAMKeychain"
pod "KVOController"
pod "FMDB"
#pod "MLeaksFinder"
#空数据页面
pod "LYEmptyView", '~> 1.0.3'
#pod "DZNPhotoPickerController"
pod "Charts"
pod "QMUIKit", '~> 4.0.0'
#高德地图SDK
pod "AMap3DMap-NO-IDFA"
pod "AMapSearch-NO-IDFA"
pod "AMapLocation-NO-IDFA"
pod "SpreadsheetView"
pod "SevenSwitch", '~> 2.1'
pod "BMPlayer", '~> 1.0.0'
pod "VehicleKeyboard-swift"
pod "OpenCV", '~> 3.4.2'
pod "Masonry"
end

